# Configuracion del servidor DHCP (Generado dinamicamente por orquestador)
option domain-name "pxe.local";
default-lease-time 600;
max-lease-time 7200;
ddns-update-style none;
authoritative;

# Red: intnet_main
subnet 192.168.1.0 netmask 255.255.255.0 {
  option subnet-mask 255.255.255.0;
  option routers 192.168.1.254;
  option domain-name-servers 8.8.8.8, 8.8.4.4;
  next-server 192.168.1.254;
  filename "pxelinux.0";
  range 192.168.1.150 192.168.1.200; # Rango dinamico

  host hotdesk-1 {
    hardware ethernet 08:00:27:00:01:00;
    fixed-address 192.168.1.100;
  }

  host hotdesk-2 {
    hardware ethernet 08:00:27:00:01:01;
    fixed-address 192.168.1.101;
  }

  host hotdesk-3 {
    hardware ethernet 08:00:27:00:01:02;
    fixed-address 192.168.1.102;
  }

  host hotdesk-4 {
    hardware ethernet 08:00:27:00:01:03;
    fixed-address 192.168.1.103;
  }

  host hotdesk-5 {
    hardware ethernet 08:00:27:00:01:04;
    fixed-address 192.168.1.104;
  }

  host hotdesk-6 {
    hardware ethernet 08:00:27:00:01:05;
    fixed-address 192.168.1.105;
  }

  host hotdesk-7 {
    hardware ethernet 08:00:27:00:01:06;
    fixed-address 192.168.1.106;
  }

  host hotdesk-8 {
    hardware ethernet 08:00:27:00:01:07;
    fixed-address 192.168.1.107;
  }

  host load-balancer {
    hardware ethernet 08:00:27:00:01:0A;
    fixed-address 192.168.1.10;
  }

  host web-frontend-1 {
    hardware ethernet 08:00:27:00:01:0B;
    fixed-address 192.168.1.11;
  }

  host web-frontend-2 {
    hardware ethernet 08:00:27:00:01:0C;
    fixed-address 192.168.1.12;
  }
}

# Red: intnet_internal
subnet 192.168.2.0 netmask 255.255.255.0 {
  option subnet-mask 255.255.255.0;
  option routers 192.168.2.254;
  option domain-name-servers 8.8.8.8, 8.8.4.4;
  next-server 192.168.2.254;
  filename "pxelinux.0";
  range 192.168.2.150 192.168.2.200; # Rango dinamico

  host cluster-master-1 {
    hardware ethernet 08:00:27:00:02:0A;
    fixed-address 192.168.2.10;
  }

  host cluster-master-2 {
    hardware ethernet 08:00:27:00:02:0B;
    fixed-address 192.168.2.11;
  }

  host cluster-worker-1 {
    hardware ethernet 08:00:27:00:02:0C;
    fixed-address 192.168.2.12;
  }

  host cluster-worker-2 {
    hardware ethernet 08:00:27:00:02:0D;
    fixed-address 192.168.2.13;
  }

  host monitoring {
    hardware ethernet 08:00:27:00:02:1E;
    fixed-address 192.168.2.30;
  }

  host storage-node {
    hardware ethernet 08:00:27:00:02:0E;
    fixed-address 192.168.2.14;
  }
}
