name: hotdesk-5
type: hotdesk
mac: "08:00:27:00:01:04"
networks:
  - name: intnet_main
    ip: "192.168.1.104"
vbox_specs:
  cpus: 1
  ram_mb: 7168
  disk_gb: 10

auth:
  username: admin
  password: "$6$CylgQV.8wYk/VUlE$UpXhP0y5NrH3ZypUfNvOF2/JEu5rRedFbseqWxsJ/dN0.XjeiK9ho.e78NWOysq/4o19qn1MolUcccrIyCjj5."

