name: storage-node
type: storage
mac: "08:00:27:00:02:0E"
networks:
  - name: intnet_internal
    ip: "192.168.2.14"
vbox_specs:
  cpus: 1
  ram_mb: 7168
  disk_gb: 30

auth:
  username: admin
  password: "$6$CylgQV.8wYk/VUlE$UpXhP0y5NrH3ZypUfNvOF2/JEu5rRedFbseqWxsJ/dN0.XjeiK9ho.e78NWOysq/4o19qn1MolUcccrIyCjj5."

